index:
    path: /
    controller: App\Controller\HomeController::index

home_path:
    path: /home
    controller: App\Controller\HomeController::index
    
article_list:
    path: /articles
    controller: App\Controller\ArticleController::index

article_id:
    path: /article/{id}/
    controller: App\Controller\ArticleController::getById

contact:
    path: /contact
    controller: App\Controller\ContactController::index

contact_handle:
    path: /contact/handle
    controller: App\Controller\ContactController::handle

about_us:
    path: /about_us
    controller: App\Controller\AboutUsController::index

login:
    path: /login
    controller: App\Controller\UserController::login

registration:
    path: /registration
    controller: App\Controller\UserController::registration

registration_handle:
    path: /registration/handle
    controller: App\Controller\UserController::handle

cart_add:
    path: /cart/add
    controller: App\Controller\CartController::add

cart_update:
    path: /cart/update
    controller: App\Controller\CartController::update

cart_delete:
    path: /cart/delete/{id}/
    controller: App\Controller\CartController::delete

order_checkout:
    path: /checkout/
    controller: App\Controller\OrderCheckoutController::index

order_handle:
    path: /order/handle
    controller: App\Controller\OrderCheckoutController::handle

order_confirm:
    path: /order/confirm/{id}
    controller: App\Controller\OrderCheckoutController::orderConfirm

order_preview:
    path: /order_preview
    controller: App\Controller\OrderCheckoutController::preview

order_pdf:
    path: /order_pdf
    controller: App\Controller\OrderCheckoutController::orderPDF

admin:
    path: /admin
    controller: App\Controller\AdminController::index

admin_about_us:
    path: /admin_about_us
    controller: App\Controller\AdminController::about

admin_contact:
    path: /admin/contacts
    controller: App\Controller\AdminController::contacts

admin_about_add:
    path: /admin/about/add
    controller: App\Controller\AboutUsController::add

admin_about_store:
    path: /admin/about/store/
    controller: App\Controller\AboutUsController::store

admin_about_edit:
    path: /admin/about/edit/{id}
    controller: App\Controller\AboutUsController::edit

admin_about_update:
    path: /admin/about/update/{$id}
    controller: App\Controller\AboutUsController::update

admin_about_delete:
    path: /admin/about/delete/{id}
    controller: App\Controller\AboutUsController::delete

admin_contact_edit:
    path: /admin/contact/edit/{id}
    controller: App\Controller\ContactController::edit

admin_contact_update:
    path: /admin/contact/update/{$id}
    controller: App\Controller\ContactController::update

admin_contact_delete:
    path: /admin/contact/delete/{id}
    controller: App\Controller\ContactController::delete

admin_articles:
    path: /showArticles
    controller: App\Controller\AdminController::showArticles 

admin_articles_add:
    path: /admin/articles/add
    controller: App\Controller\ArticleController::add

admin_articles_store:
    path: /admin/articles/store/
    controller: App\Controller\ArticleController::store

admin_articles_edit:
    path: /admin/articles/edit/{id}
    controller: App\Controller\ArticleController::edit

admin_articles_update:
    path: /admin/articles/update/{$id}
    controller: App\Controller\ArticleController::update

admin_articles_delete:
    path: /admin/articles/delete/{id}
    controller: App\Controller\ArticleController::delete

admin_users:
    path: /admin/showUsers
    controller: App\Controller\AdminController::showUsers

admin_users_add:
    path: /admin/users/add
    controller: App\Controller\UserController::add

admin_users_store:
    path: /admin/users/store/
    controller: App\Controller\UserController::store

admin_users_edit:
    path: /admin/users/edit/{id}
    controller: App\Controller\UserController::edit

admin_users_update:
    path: /admin/users/update/{$id}
    controller: App\Controller\UserController::update

admin_users_delete:
    path: /admin/users/delete/{id}
    controller: App\Controller\UserController::delete

admin_users_change_password:
    path: /admin/users/{id}/change_password
    controller: App\Controller\UserController::changePassword

admin_users_password_handler:
    path: /admin/users/{id}/password_handler/
    controller: App\Controller\UserController::passwordHandler

admin_orders:
    path: /admin/show/orders
    controller: App\Controller\AdminController::showOrders

admin_orders_detail:
    path: /admin/show/orders/detail/{id}
    controller: App\Controller\AdminController::showOrdersDetail

admin_orders_edit:
    path: /admin/orders/edit/{id}
    controller: App\Controller\OrderCheckoutController::edit

admin_orders_update:
    path: /admin/orders/update/{$id}
    controller: App\Controller\OrderCheckoutController::update

admin_orders_delete:
    path: /admin/orders/delete/{id}
    controller: App\Controller\OrderCheckoutController::delete

admin_orders_detail_edit:
    path: /admin/orders/detail/edit/{id}
    controller: App\Controller\OrderCheckoutController::editOrdersDetail

admin_orders_detail_update:
    path: /admin/orders/detail/update/{$id}
    controller: App\Controller\OrderCheckoutController::updateOrdersDetail

admin_orders_detail_delete:
    path: /admin/orders/detail/delete/{id}
    controller: App\Controller\OrderCheckoutController::deleteOrdersDetail